#!/bin/sh

choice=$(printf 'Shutdown\nReboot\nLogout\nCancel\n' |
  rofi -dmenu -i -no-show-icons -theme "$HOME/.config/rofi/powermenu.rasi")

case $choice in
Shutdown) systemctl poweroff ;;
Reboot) systemctl reboot ;;
Logout) bspc quit ;;
*) exit 0 ;;
esac
